### ISSUE TITLE
Bug: "Ignore" and "exclude" fields in .mocharc are not respected

### ISSUE THREAD

**Issue by pastelmind** [hbenl/vscode-mocha-test-adapter#125]
Mocha supports the `ignore` field in `.mocharc.*` files:

```yaml
# .mocharc.yml
spec:
  - "some/dir/*.js"
ignore:
  - "**/*.notest*.js"
```

However, Mocha Test Explorer does not recognize these fields, If I have a directory structure like this:

```
.mocharc.yml
some/
  dir/
    foo.test.js
    bar.notest.js
```

Mocha will ignore `bar.notest.js`, but Mocha Test Explorer will try to parse it as a test.

Note: `exclude` is an alias for `ignore`, but it doesn't work for Mocha Test Explorer, either.
